gui:
  language: 'zh'
  scrollHeight: 1
  showIcons: true
  showCommandLog: false
  showRandomTip: false
  mouseEvents: false
  showFileTree: false
keybinding:
  universal:
    quit: '<c-c>'
    scrollUpMain-alt1: '<up>'
    scrollDownMain-alt1: '<down>'
    moveDownCommit: 'E'
    moveUpCommit: 'U'
    prevItem: '<c-k>'
    nextItem: '<c-j>'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
