gui:
  scrollHeight: 1
  showCommandLog: true
  showRandomTip: false
  mouseEvents: false
  showFileTree: false
  language: zh-CN
keybinding:
  universal:
    quit: '<c-c>'
    scrollUpMain-alt1: '<up>'
    scrollDownMain-alt1: '<down>'
    prevItem: '<c-k>'
    nextItem: '<c-j>'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
services:
  'git.fpdev.tech': 'gitlab:git.fpdev.tech'
os:
  edit: '~/Downloads/nvim.appimage {{filename}}'
